#!/bin/bash
set -e

help() {
  cat <<EOF
Usage: gh branch

Displays an interactive branch switcher that lists local branches in relation
to the pull requests in the repository. The selected branch is checked out.

Flags:
  --static	Print a non-interactive list of branches.
  -d|--diff	Print a diff preview of the changes.
  -v|--view	Print a view of the PR description if there is one.


Dependencies: fzf
Optional dependencies: 
  glow: make \`gh branch --view\` print a pretty and colorized version of the PR view.
  	website: https://github.com/charmbracelet/glow
  bat: make \`gh branch --diff\` print a colorized version of the diff.
  	website: https://github.com/sharkdp/bat
EOF
# You can also select multiple branches with Tab and press Ctrl-D to delete them.
}

static=
diff=
view=
while [ $# -gt 0 ]; do
  case "$1" in
  -h|--help)
    help
    exit 0
    ;;
  --static)
    static=1
    ;;
  -d|--diff)
    [ -n "$view" ] && echo "view and diff can not both be set" && exit 1
    diff=1
    ;;
  -v|--view)
    [ -n "$diff" ] && echo "view and diff can not both be set" && exit 1
    view=1
    ;;
  *)
    help >&2
    exit 1
    ;;
  esac
  shift
done

branch_info() {
  git for-each-ref 'refs/heads/**' --format='%(refname:short)%09%(committerdate:unix)%09%(committerdate:relative)%09%(HEAD)'
}

list_prs() {
  gh api graphql --cache=5m -F owner='{owner}' -F repo='{repo}' -f query='
    query ($owner: String!, $repo: String!) {
      repository(owner: $owner, name: $repo) {
        pullRequests(last: 100) {
          nodes {
            number
            author {
              login
            }
            state
            headRefName
	    body
          }
        }
      }
    }
  ' --template '
    {{- range .data.repository.pullRequests.nodes -}}
      {{- .headRefName | printf "%s\t" -}}
      {{- $stateColor := "green" -}}
      {{- if eq .state "CLOSED" }}{{ $stateColor = "red" }}
      {{- else if eq .state "MERGED" }}{{ $stateColor = "magenta" }}{{ end -}}
      {{- .number | printf "\t#%.0f" | color $stateColor -}}
      {{- .author.login | printf "\tby %s\n" -}}
    {{- end -}}
  '
}

find_pr() {
  local head_branch rest
  while IFS=$'\t' read -r head_branch rest; do
    if [ "$1" = "$head_branch" ]; then
      printf "\t%s" "$rest"
      break
    fi
  done
}

render() {
  local branches branch timeago current all_prs
  branches="$(branch_info)" || return 1
  all_prs="$(list_prs 2>/dev/null || true)"
  sort -k2 -r <<<"$branches" | while IFS=$'\t' read -r branch _ timeago current _; do
    [ "$current" = "*" ] && continue
    printf "%s\t%s%s\n" "$branch" "$timeago" "$(find_pr "$branch" <<<"$all_prs")"
  done | tableize
}

tableize() {
  column -t -s$'\t'
}

if [ -n "$static" ]; then
  render
  exit 0
fi

if ! type -p fzf >/dev/null; then
  echo "error: install \`fzf\` to use this command" >&2
  exit 1
fi

choose() {
  local rendered
  rendered="$(render)" || return 1
  #--multi --bind "ctrl-d:execute-silent(git branch -D {+1})+reload(\"$0\" --static)"
  if [ -n "$view" ]; then
    fzf \
      --preview="echo {5} | cut -c2- | xargs gh pr view | if type -p glow &>/dev/null; then glow --style dark -; else cat; fi" \
      --header "<ctrl-d/u> scroll preview down/up, <ctrl-n/p> scroll next/prev PR" \
      --preview-window 'up,60%,border-bottom,+{2}+3/3,~3', \
      --bind ctrl-d:preview-down,ctrl-u:preview-up \
      --ansi <<<"$rendered"
  elif [ -n "$diff" ]; then
    fzf \
      --preview="echo {5} | cut -c2- | xargs gh pr diff | if type -p bat &>/dev/null; then bat --style=plain --color=always; else cat; fi" \
      --header "<ctrl-d/u> scroll preview down/up, <ctrl-n/p> scroll next/prev PR" \
      --preview-window 'up,60%,border-bottom,+{2}+3/3,~3', \
      --bind ctrl-d:preview-down,ctrl-u:preview-up \
      --ansi <<<"$rendered"
  else
    fzf --ansi <<<"$rendered"
  fi
}

selected="$(choose)"
[ -n "$selected" ] || exit 1
git checkout "${selected%% *}"
